plugins:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "test/dummy/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"

Style/TrivialAccessors:
  Exclude:
    - "lib/on_ramp/dsl/*.rb"

Metrics/ParameterLists:
  Exclude:
    - "lib/on_ramp/step.rb"

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Exclude:
    - "test/**/*"

Minitest/MultipleAssertions:
  Exclude:
    - "test/**/*"

Layout/LineLength:
  Exclude:
    - "*.gemspec"
